### ISSUE TITLE
`outputSelection` with contract name does not compile while compiles with `*`

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1017]
## Description
I've come across another similar case to #928. We've already worked around this by always using `*` in the selected **files**. This new case was affected by the selected **contract**.

I can see this is related to `outputSelection` being [introduced in 0.4.18](https://github.com/ethereum/solidity/blob/develop/Changelog.md#0418-2017-10-18) and updated with the selection items array [in 0.4.19](https://github.com/ethereum/solidity/blob/develop/Changelog.md#0419-2017-11-30).

Normally we set the `ouputSelection` as 
```
"*": {
  "ContractName": [
          "evm.bytecode.object",
          "evm.deployedBytecode.object",
          "evm.deployedBytecode.immutableReferences",
          "metadata"
        ]
      }
    },
```

but for this and older versions we should set it both to `*`. 

## Todo

- [ ] Double check if this is the case for all contracts earlier than 0.4.19.
  - Not for all contracts. For example v0.4.15 works for this contract [0xB4EFd85c19999D84251304bDA99E90B92300Bd93](https://etherscan.io/token/0xB4EFd85c19999D84251304bDA99E90B92300Bd93#code)
- [ ] Confirm this gets handled correctly in later versions. (Edit: See the new case below)
- [ ] Handle the `outputSelection` for contracts for these earlier versions.

## Example contract

This is an already verified contract on mainnet

Chain: Ethereum Mainnet
Address: `0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2`

version: `0.4.19+commit.c4cbbb05`

Non-working `outputSelection`:
```json
    "outputSelection": {
      "*": {
        "WETH9": [
          "evm.bytecode.object",
          "evm.deployedBytecode.object",
          "evm.deployedBytecode.immutableReferences",
          "metadata"
        ]
      }
    },
```

Working:
```json
    "outputSelection": {
      "*": {
        "*": [
          "evm.bytecode.object",
          "evm.deployedBytecode.object",
          "evm.deployedBytecode.immutableReferences",
          "metadata"
        ]
      }
    },
```

Complete JSON input:
[WETH9.json.txt](https://github.com/ethereum/solidity/files/11422405/WETH9.json.txt)

The compiler does not throw etc. but gives empty output:
```json
{
  "contracts": {
    "WETH9.sol": {
      "WETH9": {
        "evm": {
          "bytecode": {
            "linkReferences": {},
            "object": "",
            "opcodes": "",
            "sourceMap": ""
          },
          "deployedBytecode": {
            "linkReferences": {},
            "object": "",
            "opcodes": "",
            "sourceMap": ""
          }
        },
        "metadata": ""
      }
    }
  },
  "sources": {
    "WETH9.sol": {
      "id": 0
    }
  }
}
```

Source code + metadata:
[metadata.json.txt](https://github.com/ethereum/solidity/files/11422411/metadata.json.txt)
[WETH9.sol.txt](https://github.com/ethereum/solidity/files/11422412/WETH9.sol.txt)

### Another Identical Example
Chain: Binance Smart Chain Mainnet (56)
Address: `0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c`

JSON Input:
[56-0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c-solc-input.json.txt](https://github.com/ethereum/sourcify/files/11432282/56-0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c-solc-input.json.txt)

Source Code and Metadata:
[metadata.json.txt](https://github.com/ethereum/sourcify/files/11432265/metadata.json.txt)
[front_run.sol.txt](https://github.com/ethereum/sourcify/files/11432269/front_run.sol.txt)
[WBNB.sol.txt](https://github.com/ethereum/sourcify/files/11432270/WBNB.sol.txt)

**Comment by kuzdogan** [comment]
Came across another case with `v0.4.24` 

Chain: Godwoken Testnet v1 (71401)
Address: `0xE05d380839f32bC12Fb690aa6FE26B00Bd982613`

JSON input:
```json
{
  "settings": {
    "evmVersion": "byzantium",
    "libraries": {
      "": {}
    },
    "optimizer": {
      "enabled": false,
      "runs": 200
    },
    "remappings": [],
    "outputSelection": {
      "*": {
        "RollBackWithCallCodeContract": [
          "evm.bytecode.object",
          "evm.deployedBytecode.object",
          "evm.deployedBytecode.immutableReferences",
          "metadata"
        ]
      }
    },
    "metadata": {}
  },
  "sources": {
    "contracts/RollBackCallCode.sol": {
      "content": "pragma solidity ^0.4.24;\ncontract StateContract{\n\n    uint256 public state = 1;\n    function modState() public{\n        state++;\n    }\n    function modStateWithRevert() public {\n        state++;\n        revert();\n    }\n}\n\ncontract RollBackWithCallCodeContract{\n\n    uint256 public state = 1;\n\n    function getState() public view returns(uint256){\n        return state;\n    }\n    function callCodeWithMethod(string memory methodName) public {\n        StateContract sc = new StateContract();\n        address(sc).callcode(bytes4(keccak256(abi.encodePacked(methodName))));\n    }\n\n}\n"
    }
  },
  "language": "Solidity"
}
```

Compiler output:
```json
  "contracts": {
    "contracts/RollBackCallCode.sol": {
      "RollBackWithCallCodeContract": {
        "evm": {
          "bytecode": {
            "linkReferences": {},
            "object": "",
            "opcodes": "",
            "sourceMap": ""
          },
          "deployedBytecode": {
            "linkReferences": {},
            "object": "",
            "opcodes": "",
            "sourceMap": ""
          }
        },
        "metadata": ""
      },
      "StateContract": {
        "evm": {}
      }
    }
  },
```

When setting the `outputSelection` to `*`, it again successfully compiles.

The same happens with the version `v0.4.26` too. 

This leaves me wondering if this actually is because of the above mentioned `outputSelection` compatibility or if there is something else underlying.

**Comment by kuzdogan** [comment]
Opened the issue https://github.com/ethereum/solidity/issues/14214 in the Solidity repository as I couldn't really pin this down to `0.4.x` versions only and it seems to be a larger issue.

As a mitigation, and since there have been many issues regarding this, setting the `outputSelection` to be both `*`.
