### ISSUE TITLE
Improved Logging

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1291]
Tracker issue for improving the logging for debugging and monitoring purposes. This is obviously not a single run effort but will be an ongoing one.

## Description

We’re doing a fair job logging in Sourcify but we need improvements to better understand what’s going on in deployments.

This is the tracker project for such improvements, to be refined

```[tasklist]
### Tasks
- [x] Ability to turn on/off debug type logging on server and monitor
- [x] Standardizing logging in a format that shows the event type + parameters (BytecodeFetched address=0x… chain=5) instead of full form text “Bytecode fetched from chain 5 and address 0x…).
- [x] JSON logging on the deployment but line logging in development (line logging easier to read for humans)
- [x] Deciding where to throw errors and receiving alerts for such
- [x] Being able to track down a chain and address request in all logs. I.e. I can see compilation took N seconds but I don’t know which contract or from which request this is
- [x] Add `/change-log-level` secrets to deployments
```
### Logs wishlist
- [x] Removing `Won't create a WebSocketProvider` logs

### Monitoring wishlist

- [x] Total number of compiler invocations
  - [x] Verifications with solcjs
  - [x] Verifications with solc binary
- [x]  Solc versions
- [x] Total number of verification attempts (i.e. lib-sourcify calls)
