### ISSUE TITLE
[Milestone] Swapping current static endpoints to use repoV2 or the Database

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1328]
With the introduction of the database #1222 and with what we call "repoV2" we want to get rid of the legacy repository (repoV1) soon. This entails the source of truth for our APIs to be replaced with either the database or repoV1. 

Currently when someone wants to check if a contract is verified on Sourcify or get those contract files, we check the repoV1 and respond with that. With these changes we need to make use of the Database or the repoV2.

The decision to make the DB or repoV2 is TBD and will be discussed.

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/sourcify/issues/1329
- [ ] https://github.com/ethereum/sourcify/issues/1330
- [ ] https://github.com/ethereum/sourcify/issues/1398
- [x] Decide if we should replace repoV2 or the Database as the source of truth
- [ ] https://github.com/ethereum/sourcify/issues/1380
```

**Comment by kuzdogan** [comment]
Closing this as completed. The #1398 task will be done separately.
