### ISSUE TITLE
[Milestone] Tests refactoring

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1354]
The state of the server tests is quite messy. The server is mainly tested by one testfile with ~ 2000 lines. We would like to refactor the tests for improved readability and maintainability. Furthermore, since the tests are mainly integration tests, we might want to add some unit testing. We identified a few more improvements of the tests as in the following list:

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/sourcify/issues/1356
- [ ] https://github.com/ethereum/sourcify/issues/1373
- [ ] https://github.com/ethereum/sourcify/issues/1357
- [ ] https://github.com/ethereum/sourcify/issues/1358
- [ ] https://github.com/ethereum/sourcify/issues/1359
- [ ] https://github.com/ethereum/sourcify/issues/1360
- [ ] https://github.com/ethereum/sourcify/issues/1369
- [ ] https://github.com/ethereum/sourcify/issues/1382
- [ ] https://github.com/ethereum/sourcify/issues/1429
- [ ] https://github.com/ethereum/sourcify/issues/1432
- [ ] https://github.com/ethereum/sourcify/issues/1442
- [ ] https://github.com/ethereum/sourcify/issues/1428
- [ ] https://github.com/ethereum/sourcify/issues/1430
- [ ] https://github.com/ethereum/sourcify/issues/1443
```

The tasklist is only a first starting point at the moment. We will probably want to improve the tests further for this milestone.
