### ISSUE TITLE
[Milestone] APIv2 - Lookup Endpoint

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1367]
Current draft https://sourcify.stoplight.io/docs/sourcify-apiv2/branches/main

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/sourcify/issues/1646
- [ ] https://github.com/ethereum/sourcify/issues/1701
- [ ] https://github.com/ethereum/sourcify/issues/1541
- [ ] https://github.com/ethereum/sourcify/issues/1829
- [ ] https://github.com/ethereum/sourcify/issues/1830
- [ ] https://github.com/ethereum/sourcify/issues/1827
- [ ] https://github.com/ethereum/sourcify/issues/1826
- [ ] https://github.com/ethereum/sourcify/issues/1884
- [ ] https://github.com/ethereum/sourcify/issues/1831
- [ ] https://github.com/ethereum/sourcify/issues/1910
- [ ] https://github.com/ethereum/sourcify/issues/1911
- [ ] https://github.com/ethereum/sourcify/issues/1912
- [ ] https://github.com/ethereum/sourcify/issues/1828
- [ ] https://github.com/ethereum/sourcify/issues/1853
- [ ] https://github.com/ethereum/sourcify/issues/1855
- [ ] https://github.com/ethereum/sourcify/issues/1878
- [ ] https://github.com/ethereum/sourcify/issues/1877
- [ ] https://github.com/ethereum/sourcify/issues/1926
```

**Comment by kuzdogan** [comment]
Closing 🥳 For the rest of the tasks refer to https://github.com/ethereum/sourcify/issues/2033
