### ISSUE TITLE
[Milestone] Infra reset

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1425]
Tracker issue and Milestone for our move to GCP.

## Background

Sourcify deployments have been running on managed machines via Kubernetes as can be seen in https://github.com/sourcifyeth/infra

This setup hasn't been particularly working well. We had sync and communicate externally with the devops team for the management of the cluster and none of the Sourcify team members are knowledgable in this manner. Plus, the setup hasn't been able to catch up with the increasing usage. Considering we are a team of only 3, we need an infra setup that is easier to manage and scale. Even if does not align really well with the decentralization values, we have to be pragmatic at this stage, and the best option in our opinion is moving to a cloud provider. In our case we decided with GCP.

Here, I'll break down the steps and tasks required.

## UIs
- docs.sourcify.dev
  - [x] Deploying on Google Cloud Storage
  - [x] Pointing the DNS to the deployment
  - [x] Continous Deployment set up
- playground.sourcify.dev
  - [x] Deploying on Google Cloud Storage
  - [x] Pointing the DNS to the deployment
  - [x] Continous Deployment set up

### UIs
- repo.staging.sourcify.dev
  - [x] Deploying on Google Cloud
    - Not sure if this can be a Storage deployment. We need a Service that runs repo container i.e. https://github.com/sourcifyeth/h5ai-nginx 
  - [x] Pointing the DNS to the deployment
  - [x] Continous Deployment set up
- staging.sourcify.dev
  - [x] Deploying on Google Cloud Storage
  - [x] Setting up DNS and reverse proxy (see Server's DNS step)
  - [x] Continous Deployment set up

### Server

Blockers for starting the migration (i.e. recreating the database):
- https://github.com/verifier-alliance/database-specs/issues/9
- https://github.com/ethereum/sourcify/pull/1478

Steps:
- [x] ~~Pointing the running instance to the new GCP DB~~
  - Actually it's better if we don't do this because it will save files in the old repoV1 but in the new DB. Then we'll have to sync files to the new repoV1. Better leave this only to the migration job.
- [x] Run migration to recreate the DB from the existing repoV1
- [x] Deploy a new running server instance
- [x] Switch over the DNS to the new server
  - [x] Setting up a reverse proxy to accommodate both sourcify.dev/server path and sourcify.dev UI resolution
- [x] Run migration for the contracts between the prev. migration and DNS switch
  - We can run the `import-repo` script for contracts after the DNS switch date
- [x] Set up continuous deployment
- [x] Migrating the deprecated chains

### Monitor
Blocked by the Server deployment
- [x] Deploy on Google Cloud Service
  - Set max and min container count as 1
- [x] Set up Continous Deployment 
- [x] Set up a dedicated IPFS gateway

### stats-gen 
Job that generates the `/stats.json` file.

Blocked by the Server deployment

- [x] Modify the job to use the DB instead of filesystem
- [x] Deploy on GCP as recurring job

### s3-sync

Blocked by the Server deployment

- [x] Deploy on GCP as a recurring job
- [x] Back up both to GCP and Amazon

### UIs
- repo.sourcify.dev
  - [x] Deploying on Google Cloud
  - [x] Pointing the DNS to the deployment
  - [x] Continous Deployment set up
- sourcify.dev
  - [x] Deploying on Google Cloud Storage
  - [x] Setting up DNS and reverse proxy (see Server's DNS step)
  - [x] Continous Deployment set up
  
### Server

Steps:
- [x] Run migration to recreate the DB from the existing repoV1
- [x] Deploy a new running server instance
- [x] Switch over the DNS to the new server
  - [x] Setting up a reverse proxy to accommodate both sourcify.dev/server path and sourcify.dev UI resolution
- [x] Run migration for the contracts between the prev. migration and DNS switch
  - We can run the `import-repo` script for contracts after the DNS switch date
- [x] Set up continuous deployment
- [x] Migrating the deprecated chains

### Monitor
Blocked by the Server deployment
- [x] Deploy on Google Cloud Service
  - Set max and min container count as 1
- [x] Set up Continous Deployment 
- [x] Set up a dedicated IPFS gateway

### stats-gen 
Job that generates the `/stats.json` file.

Blocked by the Server deployment

- [x] Modify the job to use the DB instead of filesystem
- [x] Deploy on GCP as a recurring job

### s3-sync

- [x] Deploy on GCP as a recurring job
- [x] Back up both to GCP and Amazon

**Comment by kuzdogan** [comment]
I'd close this as we closed #1574 In the end we don't have the full S3 and IPFS setup but we have other solutions:
- Instead of S3 we do regular filesystem backups, we publish the repo regularly publicly #1586 and push to Filebase S3 regularly #1574 and #1452
- We publish the verified contract files regularly on Filebase's IPFS, although it takes long to sync everytime from the scratch, it's fine for now. Ideally we have a full-fledged IPFS service that publishes verified contract files immediately and publishes the IPNS regularly. We set it aside for now.

Congratz everyone for the achievement :)
