### ISSUE TITLE
Owneraied 

### ISSUE THREAD

**Issue by aiednt** [ethereum/sourcify#1492]
Go moon
```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/sourcify/issues/1458
- [ ] https://github.com/ethereum/sourcify/pull/1491
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/sourcify/issues/1458
- [ ] https://github.com/ethereum/sourcify/issues/1425
- [ ] https://github.com/ethereum/sourcify/pull/1484
```

**Comment by aiednt** [comment]
Go moon

**Comment by aiednt** [comment]
Owneraied

**Comment by Chator1** [comment]
Good
