### ISSUE TITLE
Sync deprecated chains to DB

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1532]
We have completed syncing existing verifications to the new DB, that is, re-verifying them using the files inside repoV1. However there are some chains that are deprecated and their RPCs are no longer available. That means their deployment data is not available, i.e. mostly the fields inside the `contract_deployments` table as well as the onchain bytecodes.

For that we need placeholder values that mark the unavailability of these data. We override those values as such:

https://github.com/ethereum/sourcify/blob/14b35301bab9dd7e092982b94daaee23919b1d97/services/server/src/server/controllers/verification/verify/stateless/verify.stateless.handlers.ts#L232-L242

```[tasklist]
### Tasks
- [x] Sync all the deprecated chains on staging
- [ ] https://github.com/ethereum/sourcify/issues/1543
- [ ] https://github.com/ethereum/sourcify/issues/1544
```
