### ISSUE TITLE
Migrate Sourcify production schema from v0 to v1

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#1672]
Issue to keep track of the migration of the production Sourcify instance, see https://github.com/ethereum/sourcify/issues/1635
```[tasklist]
### Tasks
- [x] follow migration instructions in #1635
- [x] execute post migration script to calculate `sources.source_hash_keccak` see https://github.com/ethereum/sourcify/pull/1681
- [x] Update datbase schema in documentation
```

**Comment by marcocastignoli** [comment]
**First execution in production**

|sources_inserted|links_inserted|
|----------------|--------------|
|1133346|5920686|

In 1h 5m

**Comment by marcocastignoli** [comment]
`Finished processing 1133462 rows in total`

After upgrading `source_hash_keccak` and updating the documentation the migration on production is completed.
