### ISSUE TITLE
Adapt parquet export to db v1 schema change

### ISSUE THREAD

**Issue by manuelwedler** [ethereum/sourcify#1678]
We have to adapt our parquet export script to support the recent schema changes: https://github.com/ethereum/sourcify/pull/1615

This affects the [VerA export ](https://github.com/verifier-alliance/parquet-export) and our [fork](https://github.com/sourcifyeth/parquet-export) of it.

It would be nice to implement https://github.com/ethereum/sourcify/issues/1679 beforehands.

### Tasks
- [x] Update https://github.com/verifier-alliance/parquet-export
- [x] Update https://github.com/sourcifyeth/parquet-export
- [x] Enable paused cron jobs again

**Comment by manuelwedler** [comment]
Done with https://github.com/verifier-alliance/parquet-export/commit/550c8cc4dc9eb1294adef0e8ce975264b2ea4395
