### ISSUE TITLE
Split the repository archive by match_type, chain and first byte.

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#1695]
Let's implement what discussed in #1668

Revise the repository archive generation script to generate multiple zips with the format “match_type.chain.first_byte.zip” (e.g., “full_match.1.00.zip” will contain all mainnet full_match contracts with the address starting with 00).

The file system content of the archive must be identical to the repository (`./match_type/chain/address/files`), ensuring that decompressing all the archives in the same directory will suffice to reconstruct the repository without any additional actions.
```[tasklist]
### Tasks
- [x] set up staging R2 bucket
- [x] Rework script to create zips in alphanumeric order and upload and delete directly after creation
- [x] set up new script on GCP for staging
- [x] disable old staging archive when the new archive script is up and running
- [x] set up production R2 bucket
- [x] set up new script on GCP for production
- [x] Set up domain on new production R2 bucket
- [x] disable old production archive and remove scheduler, service accounts and secret
- [x] Clean up old archive files on production and staging NFS
- [x] Delete old R2 buckets
- [x] Document the new format
```

**Comment by marcocastignoli** [comment]
Development in https://github.com/sourcifyeth/repository-chain-archiver

**Comment by kuzdogan** [comment]
lgtm

**Comment by marcocastignoli** [comment]
> [@kuzdogan](https://github.com/kuzdogan) thanks for working on this! Looks like the repo above is private. I wonder if this has an ETA?

Now it's public.

**Comment by OmarTawfik** [comment]
@marcocastignoli Thank you for the update!

 I looked into `repository-chain-archiver`, and it seems that the script is now complete (?). However, looking at [the docs](https://docs.sourcify.dev/docs/repository/file-repositories/#download), it seems that it is still describing the old zip files (that need to be concatenated together first to be processed).

I wonder if there is an ETA to start publishing the individual split zip files with the new format?

**Comment by marcocastignoli** [comment]
> @marcocastignoli Thank you for the update!
> 
>  I looked into `repository-chain-archiver`, and it seems that the script is now complete (?). However, looking at [the docs](https://docs.sourcify.dev/docs/repository/file-repositories/#download), it seems that it is still describing the old zip files (that need to be concatenated together first to be processed).
> 
> I wonder if there is an ETA to start publishing the individual split zip files with the new format?

The new script is not live yet. During the Devcon week we are slowing down on the development. I'll finalize this asap. Thanks for your interest

**Comment by manuelwedler** [comment]
@OmarTawfik the new format is available at https://repo-backup.sourcify.dev/
