### ISSUE TITLE
Outreach plan

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1763]
Over the last few months we have been deprioritizing the visibility and the outreach of the project and focusing on the technical development. Now that the server is rather reliable we should shift our focus to bring more visibility to Sourcify.

Here I'll be keeping track of ideas and tasks.
```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/sourcify/issues/1764
- [x] Fix Matrix/Discord bridge
- [x] Announce mekong support (after release) https://github.com/ethereum/sourcify/pull/1747
- [ ] ~~Write a blog post about the Verifier Alliance~~
- [x] Write a blog post about "What is source code verification"
```
