### ISSUE TITLE
Cannot handle multiple source code files from Etherscan

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#947]
Import from Etherscan fails for the contract: https://etherscan.io/address/0xB753548F6E010e7e680BA186F9Ca1BdAB2E90cf2#code

The reason it seems, that it's neither a single source code file contract, nor a standard-json contract. We are not handling "Solidity Multiple files format" of Etherscan.

### TODO:
- [ ] Etherscan Handle Solidity Multiple files format 

Add tests for parsing (if does not exist)
  - [ ] Single file Etherscan contracts
  - [ ] Solidity Multiple files format contracts
  - [ ] Standard-json contracts

**Comment by marcocastignoli** [comment]
we already have this:

https://github.com/ethereum/sourcify/blob/3c13af8e5c9af83c449df296b5563dcd54e6d339/src/server/controllers/VerificationController-util.ts#L582..L593
```typescript
  let solcJsonInput;
  // SourceCode can be the Solidity code if there is only one contract file, or the json object if there are multiple files
  if (contractHasMultipleFiles(sourceCodeObject)) {
    solcJsonInput = parseMultipleFilesContract(sourceCodeObject);
    // Tell compiler to output metadata
    solcJsonInput.settings.outputSelection["*"]["*"] = ["metadata"];
  } else {
    const contractPath = contractResultJson.ContractName + ".sol";
    solcJsonInput = getSolcJsonInputFromEtherscanResult(
      contractResultJson,
      contractPath
    );
  }
```
